set search_path to medical;

-- contact
insert into contact (phone_number, email, profile_link) values ('861-838-9638', 'gcharlesworth0@jimdo.com', 'unicef.org');
insert into contact (phone_number, email, profile_link) values ('991-907-9324', 'sfligg1@goo.ne.jp', 'booking.com');
insert into contact (phone_number, email, profile_link) values ('301-541-0222', 'tbelshaw2@indiegogo.com', 'addtoany.com');
insert into contact (phone_number, email, profile_link) values ('784-204-8675', 'ghendonson3@hud.gov', 'paginegialle.it');
insert into contact (phone_number, email, profile_link) values ('694-353-2298', 'rlorain4@independent.co.uk', 'arstechnica.com');
insert into contact (phone_number, email, profile_link) values ('822-250-4689', 'sgoldhawk5@ovh.net', 'macromedia.com');
insert into contact (phone_number, email, profile_link) values ('373-528-1599', 'npowton6@stanford.edu', '123-reg.co.uk');
insert into contact (phone_number, email, profile_link) values ('782-332-2904', 'smcgrorty7@unc.edu', 'yolasite.com');
insert into contact (phone_number, email, profile_link) values ('318-231-9059', 'aeveriss8@geocities.com', 'issuu.com');
insert into contact (phone_number, email, profile_link) values ('691-329-9211', 'ngiovanardi9@dailymotion.com', 'admin.ch');
insert into contact (phone_number, email, profile_link) values ('630-325-3749', 'svanrossa@ted.com', 'theatlantic.com');
insert into contact (phone_number, email, profile_link) values ('167-863-5584', 'ygensavageb@vinaora.com', 'vkontakte.ru');
insert into contact (phone_number, email, profile_link) values ('819-951-8621', 'bfeldbergerc@dyndns.org', 'weibo.com');
insert into contact (phone_number, email, profile_link) values ('997-982-4279', 'lvallowd@youku.com', 'discovery.com');
insert into contact (phone_number, email, profile_link) values ('932-819-3845', 'cblodgete@bloglines.com', '51.la');
insert into contact (phone_number, email, profile_link) values ('957-597-6435', 'lvollethf@yolasite.com', 'ycombinator.com');
insert into contact (phone_number, email, profile_link) values ('271-169-9951', 'lchildrensg@fotki.com', 'yelp.com');
insert into contact (phone_number, email, profile_link) values ('788-752-8408', 'ptilletth@storify.com', 'example.com');
insert into contact (phone_number, email, profile_link) values ('492-874-9268', 'bjezzardi@tumblr.com', 'example.com');
insert into contact (phone_number, email, profile_link) values ('878-941-0233', 'rdelgardilloj@twitter.com', 'marketwatch.com');
insert into contact (phone_number, email, profile_link) values ('851-928-6278', 'mdeliask@purevolume.com', 'netscape.com');
insert into contact (phone_number, email, profile_link) values ('243-410-9243', 'cpresdeel@hp.com', 'histats.com');
insert into contact (phone_number, email, profile_link) values ('432-490-2216', 'wfaunchm@skype.com', 'sciencedirect.com');
insert into contact (phone_number, email, profile_link) values ('425-484-5455', 'bpridmoren@si.edu', 'surveymonkey.com');
insert into contact (phone_number, email, profile_link) values ('734-562-9683', 'ladameco@ibm.com', 'fastcompany.com');
insert into contact (phone_number, email, profile_link) values ('803-682-5175', 'malebrookep@constantcontact.com', 'twitpic.com');
insert into contact (phone_number, email, profile_link) values ('214-898-9538', 'bklaffq@unesco.org', 'apple.com');
insert into contact (phone_number, email, profile_link) values ('464-781-0788', 'cagiolfingerr@gov.uk', 'comcast.net');
insert into contact (phone_number, email, profile_link) values ('510-988-7003', 'agaskals@rediff.com', 'macromedia.com');
insert into contact (phone_number, email, profile_link) values ('271-738-1573', 'cbarltropt@google.nl', 'ft.com');
insert into contact (phone_number, email, profile_link) values ('225-652-7802', 'gheballu@studiopress.com', 'elegantthemes.com');
insert into contact (phone_number, email, profile_link) values ('151-512-3827', 'wwiggettv@xing.com', 'irs.gov');
insert into contact (phone_number, email, profile_link) values ('290-553-9138', 'fgrangierw@wordpress.com', 'sphinn.com');
insert into contact (phone_number, email, profile_link) values ('723-722-0359', 'jmcgrannx@etsy.com', 'jigsy.com');
insert into contact (phone_number, email, profile_link) values ('380-929-0016', 'ftowly@guardian.co.uk', 'goo.gl');
insert into contact (phone_number, email, profile_link) values ('144-392-8986', 'koriganz@4shared.com', 'xing.com');
insert into contact (phone_number, email, profile_link) values ('958-878-1387', 'lcurado10@guardian.co.uk', 'i2i.jp');
insert into contact (phone_number, email, profile_link) values ('867-385-4325', 'oribchester11@1und1.de', 'wikia.com');
insert into contact (phone_number, email, profile_link) values ('797-826-3896', 'dblack12@com.com', 'friendfeed.com');
insert into contact (phone_number, email, profile_link) values ('652-501-6441', 'papplebee13@economist.com', 'ebay.co.uk');
insert into contact (phone_number, email, profile_link) values ('986-427-3405', 'alochet14@ted.com', 'about.me');
insert into contact (phone_number, email, profile_link) values ('818-179-6237', 'pheinle15@technorati.com', 'list-manage.com');
insert into contact (phone_number, email, profile_link) values ('503-155-6637', 'rjosse16@etsy.com', 'friendfeed.com');
insert into contact (phone_number, email, profile_link) values ('262-678-9119', 'tgiacovazzo17@uol.com.br', 'elegantthemes.com');
insert into contact (phone_number, email, profile_link) values ('561-136-6032', 'lbazell18@wix.com', 'salon.com');
insert into contact (phone_number, email, profile_link) values ('372-949-8434', 'hcadle19@cbc.ca', 'cnbc.com');
insert into contact (phone_number, email, profile_link) values ('523-630-6502', 'skell1a@statcounter.com', 'addthis.com');
insert into contact (phone_number, email, profile_link) values ('260-273-4765', 'hpenhaligon1b@patch.com', 'dmoz.org');
insert into contact (phone_number, email, profile_link) values ('117-100-8812', 'rmolian1c@soundcloud.com', 'wufoo.com');
insert into contact (phone_number, email, profile_link) values ('179-106-8741', 'fduprey1d@statcounter.com', 'ehow.com');
insert into contact (phone_number, email, profile_link) values ('395-174-1635', 'bpercifer1e@smh.com.au', 'mlb.com');
insert into contact (phone_number, email, profile_link) values ('384-281-0095', 'darran1f@live.com', 'so-net.ne.jp');
insert into contact (phone_number, email, profile_link) values ('220-479-9482', 'fsarre1g@google.com.hk', 'ehow.com');
insert into contact (phone_number, email, profile_link) values ('293-792-8981', 'ehalligan1h@mapy.cz', 'cam.ac.uk');
insert into contact (phone_number, email, profile_link) values ('241-785-6606', 'dmahaddie1i@java.com', 'miitbeian.gov.cn');
insert into contact (phone_number, email, profile_link) values ('570-686-0752', 'cjacquest1j@blogs.com', 'gnu.org');
insert into contact (phone_number, email, profile_link) values ('893-438-9671', 'bondrousek1k@cpanel.net', 'shop-pro.jp');
insert into contact (phone_number, email, profile_link) values ('105-964-3757', 'pklimkovich1l@blogs.com', 'cdc.gov');
insert into contact (phone_number, email, profile_link) values ('528-484-3403', 'rcapehorn1m@oracle.com', '4shared.com');
insert into contact (phone_number, email, profile_link) values ('345-115-3692', 'lwooddisse1n@weather.com', 'naver.com');
insert into contact (phone_number, email, profile_link) values ('625-128-8681', 'dcronk1o@ehow.com', 'gnu.org');
insert into contact (phone_number, email, profile_link) values ('608-234-3761', 'ygurnell1p@nifty.com', 'creativecommons.org');
insert into contact (phone_number, email, profile_link) values ('908-569-0189', 'babarough1q@biblegateway.com', 'cornell.edu');
insert into contact (phone_number, email, profile_link) values ('672-506-5748', 'ajurewicz1r@webmd.com', '163.com');
insert into contact (phone_number, email, profile_link) values ('308-894-4590', 'agibbins1s@woothemes.com', 'topsy.com');
insert into contact (phone_number, email, profile_link) values ('647-749-7182', 'ryurkevich1t@sphinn.com', 'shareasale.com');
insert into contact (phone_number, email, profile_link) values ('142-223-7848', 'gbeden1u@webs.com', 'multiply.com');
insert into contact (phone_number, email, profile_link) values ('735-513-3093', 'ddalliwatr1v@fastcompany.com', 'hostgator.com');
insert into contact (phone_number, email, profile_link) values ('297-633-2370', 'mlejean1w@imageshack.us', 'infoseek.co.jp');
insert into contact (phone_number, email, profile_link) values ('555-756-8716', 'swikey1x@cmu.edu', 'sciencedirect.com');
insert into contact (phone_number, email, profile_link) values ('725-955-1054', 'cardern1y@cbsnews.com', 'twitter.com');
insert into contact (phone_number, email, profile_link) values ('303-707-0832', 'blankham1z@archive.org', 'mediafire.com');
insert into contact (phone_number, email, profile_link) values ('909-914-2879', 'mmary20@cbsnews.com', 'issuu.com');
insert into contact (phone_number, email, profile_link) values ('297-846-0280', 'coxterby21@wikispaces.com', 'yelp.com');
insert into contact (phone_number, email, profile_link) values ('843-170-9143', 'gcastro22@google.de', 'google.it');
insert into contact (phone_number, email, profile_link) values ('315-663-4033', 'dlawerence23@youtube.com', 'vistaprint.com');
insert into contact (phone_number, email, profile_link) values ('561-683-1218', 'rgirardeau24@vimeo.com', 'rambler.ru');
insert into contact (phone_number, email, profile_link) values ('836-373-4247', 'vmcgraw25@acquirethisname.com', 'mtv.com');
insert into contact (phone_number, email, profile_link) values ('349-727-0035', 'dneed26@chicagotribune.com', 'wordpress.com');
insert into contact (phone_number, email, profile_link) values ('479-497-0892', 'mrigardeau27@uiuc.edu', 'spiegel.de');
insert into contact (phone_number, email, profile_link) values ('777-973-6764', 'wrickaert28@angelfire.com', 'tripadvisor.com');
insert into contact (phone_number, email, profile_link) values ('916-647-9065', 'lchadderton29@mail.ru', 'senate.gov');
insert into contact (phone_number, email, profile_link) values ('758-960-2092', 'alangelaan2a@imdb.com', 'nasa.gov');
insert into contact (phone_number, email, profile_link) values ('556-143-1509', 'tpinsent2b@apple.com', 'rambler.ru');
insert into contact (phone_number, email, profile_link) values ('353-133-7458', 'ybeadman2c@last.fm', 'free.fr');
insert into contact (phone_number, email, profile_link) values ('792-784-3244', 'adangelo2d@salon.com', 'theatlantic.com');
insert into contact (phone_number, email, profile_link) values ('679-771-2234', 'vavard2e@digg.com', 'livejournal.com');
insert into contact (phone_number, email, profile_link) values ('537-210-9655', 'mshermar2f@uiuc.edu', 'topsy.com');
insert into contact (phone_number, email, profile_link) values ('194-172-2138', 'efiddler2g@home.pl', 'google.it');
insert into contact (phone_number, email, profile_link) values ('482-671-5235', 'pbrookson2h@sina.com.cn', 'rediff.com');
insert into contact (phone_number, email, profile_link) values ('219-639-4983', 'hdurtnel2i@360.cn', 'ftc.gov');
insert into contact (phone_number, email, profile_link) values ('115-149-6614', 'elievesley2j@slashdot.org', 'yandex.ru');
insert into contact (phone_number, email, profile_link) values ('441-391-0124', 'iayscough2k@squidoo.com', 'umich.edu');
insert into contact (phone_number, email, profile_link) values ('344-601-7521', 'epole2l@yellowpages.com', 'mayoclinic.com');
insert into contact (phone_number, email, profile_link) values ('526-457-3339', 'knassi2m@cocolog-nifty.com', 'tinypic.com');
insert into contact (phone_number, email, profile_link) values ('565-205-8429', 'bnichols2n@google.co.jp', 'nbcnews.com');
insert into contact (phone_number, email, profile_link) values ('213-448-6854', 'acorkel2o@last.fm', 'google.it');
insert into contact (phone_number, email, profile_link) values ('798-139-3489', 'apochin2p@amazon.co.uk', 'cafepress.com');
insert into contact (phone_number, email, profile_link) values ('668-114-6977', 'nkardosstowe2q@japanpost.jp', 'nydailynews.com');
insert into contact (phone_number, email, profile_link) values ('568-598-6871', 'bbrouard2r@ted.com', 'amazon.com');

-- address
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 48, 'Pawili', 17338, 'Larry', 11, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 48, 'Pawili', 17338, 'Larry', 11, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 48, 'Pawili', 17338, 'Larry', 11, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 48, 'Pawili', 17338, 'Larry', 11, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (97, 73, 'Montor Timur', 16153, 'New Castle', 10, 710);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (71, 76, 'Shangtian', 18351, 'Roth', 15, 830);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (19, 22, 'Nowa Dęba', 10098, 'Raven', 2, 840);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (80, 34, 'Shuangxiqiao', 11936, 'Cordelia', 3, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (80, 34, 'Shuangxiqiao', 11936, 'Cordelia', 3, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (80, 34, 'Shuangxiqiao', 11936, 'Cordelia', 3, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (80, 34, 'Shuangxiqiao', 11936, 'Cordelia', 3, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (4, 55, 'Koski Tl', 12115, 'Norway Maple', 7, 550);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (33, 45, 'Huangkeng', 14983, 'Crescent Oaks', 7, 420);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (60, 23, 'Al Ḩāmūl', 17293, 'Montana', 13, 190);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (73, 41, 'Jalatrang', 17774, 'Northport', 12, 880);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (40, 40, 'Guanay', 13570, 'Tomscot', 1, 140);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (54, 19, 'Meipu', 10768, 'Pierstorff', 11, 670);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (61, 70, 'Reforma', 17318, 'Hollow Ridge', 19, 340);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (15, 62, 'Tagog', 17099, 'Hooker', 11, 160);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (73, 35, 'Iwakuni', 14439, 'Lakewood Gardens', 4, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (87, 75, 'Stuttgart', 16779, 'Miller', 9, 630);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (45, 87, '''s-Hertogenbosch', 16110, '8th', 2, 330);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (31, 84, 'Lemland', 10849, 'Dahle', 10, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (55, 83, 'Sedayu', 12864, 'Eggendart', 12, 860);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (62, 36, 'Ijero-Ekiti', 12480, '3rd', 4, 210);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (74, 97, 'Bettendorf', 17510, 'Springs', 20, 890);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (33, 12, 'Lagoa', 15826, 'Knutson', 20, 560);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (75, 12, 'Curahkalak Tengah', 15629, 'Waywood', 5, 200);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (39, 100, 'Krasnyye Barrikady', 12644, 'Grim', 17, 300);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (91, 53, 'Kashirskoye', 13215, 'Eastwood', 16, 390);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (59, 78, 'Falkenberg', 11811, 'Pearson', 18, 650);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (29, 46, 'Los Aquijes', 11272, 'Bultman', 4, 710);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (11, 93, 'Maslovka', 12833, 'Basil', 17, 640);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (32, 79, 'Chengjiang', 16048, 'Clyde Gallagher', 10, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (63, 30, 'Clermont-Ferrand', 11342, 'Brentwood', 1, 820);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (1, 63, 'Chamical', 15983, 'Grayhawk', 8, 540);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (68, 16, 'Farmington', 13039, 'Shoshone', 8, 540);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (85, 43, 'Guarujá', 17135, 'Rigney', 16, 540);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (61, 16, 'Sinazongwe', 12030, 'Morningstar', 14, 640);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (45, 28, 'Naikoten Dua', 15940, 'Browning', 16, 890);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (3, 84, 'Calimete', 12588, 'Oriole', 7, 510);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (95, 81, 'Fort Wayne', 17037, 'Northfield', 15, 240);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (19, 71, 'Dasha', 13229, 'Dexter', 5, 780);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (39, 29, 'Uglyanets', 14694, 'Talisman', 5, 230);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (10, 30, 'Talitsa', 14938, 'Blackbird', 14, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (75, 75, 'Kopparberg', 18148, 'Fulton', 12, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (52, 27, 'Hongsihu', 16489, 'Pawling', 4, 390);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (85, 1, 'Manutapen', 15601, 'Holy Cross', 20, 690);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (26, 58, 'Leipzig', 16246, 'Dayton', 13, 490);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (62, 33, 'Xitiangezhuang', 15641, 'Magdeline', 3, 610);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (29, 96, 'Sumberpandan', 14946, 'Hayes', 14, 300);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (90, 79, 'Colonia Minga Porá', 11340, 'Hintze', 20, 680);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (24, 12, 'Sant Cugat Del Valles', 10341, 'Katie', 8, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (50, 20, 'Anyar', 17692, 'Duke', 3, 830);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (28, 61, 'Roissy Charles-de-Gaulle', 10260, 'Maryland', 13, 300);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (76, 51, 'Postupice', 11854, 'Mariners Cove', 9, 620);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (88, 57, 'Gorzkowice', 13450, 'American Ash', 14, 410);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (89, 33, 'El Soberbio', 12997, 'Moulton', 5, 540);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (47, 50, 'Magomeni', 17088, 'Judy', 14, 770);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (86, 38, 'San Jerónimo', 16337, 'Browning', 19, 850);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (85, 12, 'Pingshan', 17365, 'Stone Corner', 15, 690);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (4, 83, 'Magatos', 18724, 'Bay', 3, 130);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (95, 82, 'Aqqan', 14031, 'Green', 6, 120);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (75, 77, 'Siderejo', 18475, 'Dexter', 1, 510);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (77, 90, 'Březová nad Svitavou', 16523, '8th', 15, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (45, 9, 'Ngajum', 10523, 'Welch', 5, 470);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (53, 22, 'Ningtang', 13729, 'Moland', 10, 140);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (76, 41, 'Sintung Timur', 17564, 'Lakewood', 1, 430);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (3, 15, 'Roma', 16029, 'Bayside', 10, 150);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 31, 'Skotoússa', 17959, 'Vernon', 8, 400);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (75, 54, 'Arnoia', 11272, 'Judy', 7, 330);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (38, 32, 'Carrasqueira', 11366, 'Prentice', 5, 450);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (41, 13, 'Luofang', 17604, 'Gerald', 7, 630);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (5, 73, 'Eaubonne', 13199, 'Forest Run', 16, 600);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (47, 4, 'Loughrea', 10021, 'Harper', 10, 520);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (4, 34, 'Cuauhtemoc', 14770, 'Ludington', 14, 870);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (79, 100, 'Sājir', 17539, 'Mitchell', 3, 740);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (91, 10, 'Kuleqi', 18049, 'Roth', 8, 900);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (29, 72, 'Ramos', 12186, 'Prentice', 2, 570);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (32, 7, 'Lazaro Cardenas', 17568, 'Logan', 11, 390);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (85, 15, 'Ponte Nova', 11546, 'Tennessee', 17, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (16, 84, 'Mariestad', 15423, 'Bluejay', 17, 120);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (45, 99, 'Bulog', 13802, 'Golf Course', 19, 360);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (84, 90, 'Zhongling', 12319, 'Washington', 17, 130);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (75, 96, 'Badean', 13858, 'Towne', 11, 150);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (25, 66, 'Kobylin', 13738, 'Mccormick', 8, 680);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (58, 36, 'Sulangan', 10041, 'Mitchell', 16, 870);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (40, 5, 'Dongmazar', 17288, 'Brickson Park', 10, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (70, 64, 'Ramalhal', 18034, 'Northwestern', 16, 360);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (57, 70, 'Suqin Huimin', 12249, 'Nevada', 12, 700);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (42, 43, 'Kukushtan', 18048, 'Mayfield', 19, 170);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (3, 81, 'Granada', 16602, 'Pawling', 11, 830);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (79, 22, 'Machinda', 18265, 'Scofield', 15, 170);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (92, 46, 'Batiano', 11242, 'Nelson', 8, 530);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (4, 67, 'Sarajevo', 11562, 'Redwing', 10, 260);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (55, 55, 'Hulu', 16068, 'Moulton', 3, 730);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (7, 88, 'Tuanlin', 12215, 'Dorton', 6, 650);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (14, 58, 'Paraíso', 10869, 'Anzinger', 19, 860);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (61, 4, 'Paninggaran', 15458, 'Michigan', 5, 330);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (46, 46, 'Seredyna-Buda', 13277, 'Tennessee', 7, 620);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (85, 62, 'Quintães', 10402, 'Atwood', 12, 270);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (1, 61, 'Apeldoorn', 18952, 'American', 15, 280);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (37, 32, 'Uspenka', 10860, 'Londonderry', 16, 810);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (33, 10, 'Лабуништа', 13855, 'Commercial', 9, 120);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (16, 53, 'Al Başrah', 11286, 'Buena Vista', 6, 330);
insert into address (contact_id, country_id, city, index, street, buildings, flat) values (55, 42, 'Novomichurinsk', 15567, 'Gulseth', 19, 770);

-- medical_card
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', null, '7/13/2022', 'vel est donec');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '4/15/2022', 'tempus semper');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', null, '11/28/2021', 'sem praesent id massa');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '8/24/2022', 'sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '3/20/2022', 'risus praesent lectus vestibulum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '9/20/2022', 'dapibus augue');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '4/2/2022', 'id massa id nisl');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '10/8/2022', 'commodo vulputate justo in');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '8/10/2022', 'luctus rutrum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '4/25/2022', 'id justo sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/12/2022', 'justo sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '1/31/2022', 'id luctus nec');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '2/28/2022', 'dolor sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '4/16/2022', 'sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '10/27/2021', 'posuere metus');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '6/30/2022', 'nibh ligula nec');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '1/20/2022', 'dui maecenas tristique');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '1/9/2022', 'ultricies eu nibh');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '1/19/2022', 'semper sapien a libero');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '8/15/2022', 'tempus sit');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '10/6/2022', 'interdum venenatis turpis');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '7/1/2022', 'ac tellus semper');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '1/6/2022', 'eget eleifend luctus');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '4/18/2022', 'erat curabitur');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '6/25/2022', 'nascetur ridiculus mus etiam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/20/2022', 'consequat varius');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '1/26/2022', 'amet consectetuer adipiscing');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '10/29/2021', 'sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '3/30/2022', 'curabitur in');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '6/13/2022', 'hac habitasse');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '8/8/2022', 'enim sit amet nunc');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/11/2022', 'pellentesque ultrices');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/5/2022', 'aliquet pulvinar');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '2/22/2022', 'orci mauris lacinia sapien');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/19/2022', 'ultrices posuere cubilia');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '2/13/2022', 'luctus et ultrices posuere');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '2/4/2022', 'vel ipsum praesent blandit');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '11/25/2021', 'luctus rutrum nulla tellus');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '4/5/2022', 'non lectus');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '12/23/2021', 'amet nunc');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '3/27/2022', 'massa quis augue');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '8/16/2022', 'elit sodales scelerisque');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '3/27/2022', 'luctus cum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '1/2/2022', 'diam cras pellentesque');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '11/16/2021', 'aliquam sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '7/22/2022', 'iaculis diam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '8/16/2022', 'dignissim vestibulum vestibulum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '11/3/2021', 'imperdiet sapien');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '2/14/2022', 'dui vel nisl');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '9/18/2022', 'non pretium');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '1/5/2022', 'proin at turpis a');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '10/7/2022', 'in porttitor pede justo');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '5/28/2022', 'sit amet sem fusce');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '7/4/2022', 'quam pede');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '8/22/2022', 'nec nisi volutpat eleifend');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '12/30/2021', 'felis eu');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '9/8/2022', 'consequat morbi a');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '9/24/2022', 'turpis nec euismod scelerisque');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '4/4/2022', 'venenatis lacinia');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '7/28/2022', 'donec diam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '5/5/2022', 'libero nullam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '1/8/2022', 'congue elementum in hac');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '8/9/2022', 'nulla ultrices');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '10/2/2022', 'ultrices enim lorem');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '5/25/2022', 'in felis donec semper');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '9/3/2022', 'nec dui luctus rutrum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '12/2/2021', 'donec odio');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '3/27/2022', 'aenean sit amet');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '1/2/2022', 'vel est');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '4/10/2022', 'lacus at velit');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/20/2022', 'ipsum primis in');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '6/10/2022', 'mauris non ligula');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '4/25/2022', 'non mauris morbi non');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '6/22/2022', 'justo pellentesque viverra');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '7/9/2022', 'donec diam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '3/23/2022', 'sem praesent');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '4/22/2022', 'in faucibus');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '7/8/2022', 'tempor convallis');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '10/21/2022', 'pulvinar sed nisl nunc');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '9/27/2022', 'dolor quis');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '6/11/2022', 'urna pretium nisl ut');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '12/20/2021', 'magnis dis parturient');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '7/27/2022', 'cursus id turpis integer');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '4/1/2022', 'quisque erat eros viverra');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '5/15/2022', 'tempus semper est');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '6/17/2022', 'justo aliquam quis');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '3/8/2022', 'a feugiat et');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '10/16/2022', 'justo nec condimentum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '11/7/2021', 'porttitor lorem id');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '10/20/2022', 'lorem quisque ut');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '12/25/2021', 'ante ipsum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'M', '4/26/2022', 'morbi porttitor');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '12/17/2021', 'interdum eu tincidunt in');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'F', '9/30/2022', 'et ultrices');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '11/16/2021', 'non velit donec diam');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '9/30/2022', 'rhoncus dui vel');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '8/15/2022', 'diam cras pellentesque');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('M', 'M', '5/29/2022', 'ut mauris');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '4/1/2022', 'ac tellus semper interdum');
insert into medical_card (client_status, med_status, registry_dt, comment) values ('F', 'F', '8/11/2022', 'turpis eget');

-- illness
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (17, 89, 'M', '2021-12-21 09:40:03', '7/22/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (21, 93, 'F', '2022-05-24 20:20:41', '6/8/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (98, 41, 'M', '2022-06-29 05:17:13', '10/28/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 81, 'M', '2022-07-28 01:42:00', '11/10/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (92, 45, 'M', '2022-05-13 21:29:09', '1/3/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (46, 85, 'F', '2021-11-16 03:47:29', '5/8/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (41, 25, 'F', '2022-10-16 17:20:04', '6/10/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 9, 'M', '2022-09-09 21:26:26', '5/1/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (4, 13, 'M', '2021-11-25 20:22:23', '5/22/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (22, 39, 'F', '2022-08-18 05:34:17', '3/25/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (25, 79, 'M', '2021-10-29 12:03:29', '12/11/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (75, 44, 'F', '2022-01-13 01:19:12', '10/7/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (85, 56, 'F', '2022-04-09 14:32:17', '11/5/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (78, 67, 'M', '2022-08-20 20:20:02', '4/10/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (56, 43, 'M', '2022-04-30 02:26:05', '1/18/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 53, 'M', '2022-07-12 21:14:21', '9/24/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (34, 40, 'M', '2022-03-07 15:45:44', '9/16/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (96, 91, 'F', '2021-12-20 22:44:52', '3/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (44, 81, 'M', '2022-01-09 15:31:33', '10/23/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (34, 37, 'F', '2022-02-02 23:57:13', '5/14/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (80, 26, 'F', '2022-02-27 00:45:10', '2/4/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (67, 98, 'M', '2022-07-16 11:08:14', '3/25/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (95, 72, 'M', '2022-05-28 09:06:14', '11/14/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (48, 15, 'M', '2021-12-03 21:26:46', '6/5/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (15, 77, 'M', '2022-07-25 22:49:33', '10/1/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (58, 35, 'M', '2021-12-31 06:27:01', '1/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (17, 8, 'F', '2022-03-26 13:58:02', '11/26/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (16, 32, 'M', '2022-03-25 18:55:52', '3/24/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (37, 61, 'F', '2022-07-02 10:54:46', '3/14/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (71, 63, 'F', '2022-01-19 13:21:50', '6/22/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (58, 32, 'F', '2022-07-25 08:53:44', '11/2/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (13, 16, 'F', '2022-03-18 13:11:58', '7/24/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (66, 25, 'F', '2022-04-17 22:25:37', '3/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (60, 39, 'M', '2022-04-12 09:03:03', '2/17/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (22, 98, 'M', '2022-06-03 08:47:02', '10/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (39, 6, 'F', '2022-07-17 14:40:40', '6/5/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (63, 89, 'F', '2022-01-23 05:01:01', '1/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (75, 47, 'M', '2022-04-23 17:57:19', '4/4/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (81, 26, 'M', '2021-11-09 11:22:31', '11/25/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (29, 100, 'F', '2022-08-10 08:12:33', '11/25/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (15, 89, 'F', '2022-01-17 19:53:48', '10/27/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (26, 27, 'F', '2022-01-30 14:02:53', '11/6/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (28, 54, 'F', '2022-06-14 15:49:16', '9/15/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (33, 16, 'F', '2021-12-03 06:14:17', '8/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (17, 24, 'F', '2021-10-28 18:32:47', '5/25/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (59, 70, 'M', '2021-12-05 18:56:10', '4/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (60, 20, 'F', '2022-02-15 12:13:02', '4/12/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (99, 79, 'M', '2022-08-06 10:04:16', '10/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (87, 66, 'M', '2022-03-14 08:29:27', '12/4/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (58, 30, 'F', '2022-02-28 18:13:17', '3/19/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (94, 81, 'M', '2022-06-03 09:02:09', '3/6/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (98, 6, 'F', '2022-02-02 07:22:28', '8/13/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (51, 21, 'M', '2022-09-23 08:28:45', '2/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (57, 64, 'F', '2022-07-14 07:05:36', '11/20/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (12, 15, 'F', '2022-01-05 20:33:24', '6/15/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (9, 75, 'M', '2021-11-22 07:16:47', '1/11/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (32, 57, 'F', '2021-10-27 09:29:33', '2/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (43, 12, 'M', '2022-04-12 16:33:56', '4/9/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (69, 40, 'M', '2022-08-21 10:42:16', '6/16/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (56, 79, 'F', '2022-07-12 08:30:54', '12/23/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (11, 11, 'F', '2022-09-30 03:22:02', '8/27/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (64, 43, 'F', '2022-10-18 23:51:14', '6/28/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (57, 91, 'F', '2022-10-21 21:17:26', '9/11/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (15, 75, 'F', '2022-09-04 17:04:56', '2/6/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (92, 39, 'M', '2022-07-01 17:42:20', '5/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (86, 69, 'M', '2021-10-28 19:23:30', '10/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (93, 66, 'F', '2021-11-05 15:49:17', '10/8/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (100, 28, 'F', '2022-08-26 07:55:53', '6/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (49, 84, 'F', '2022-10-08 10:13:30', '10/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (8, 82, 'F', '2022-02-24 13:39:09', '1/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (8, 32, 'M', '2022-10-09 13:30:18', '10/2/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (19, 45, 'F', '2022-09-22 23:05:40', '6/11/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (85, 44, 'F', '2021-10-26 01:38:50', '10/9/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (19, 20, 'F', '2022-02-21 08:02:22', '1/27/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (87, 61, 'M', '2021-11-14 08:02:23', '9/6/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (71, 76, 'M', '2022-03-26 15:56:44', '2/20/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 58, 'F', '2022-01-08 04:48:40', '8/11/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (50, 41, 'M', '2022-03-15 20:22:58', '5/16/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (67, 28, 'F', '2022-03-15 19:02:35', '8/20/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (10, 8, 'M', '2021-12-08 04:00:18', '12/31/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (20, 82, 'F', '2022-04-11 22:31:33', '10/3/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (78, 24, 'F', '2022-07-08 20:27:21', '3/28/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (48, 50, 'F', '2022-09-02 22:15:00', '11/3/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (8, 41, 'F', '2022-03-18 01:01:46', '5/29/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (59, 14, 'F', '2022-06-24 08:51:47', '6/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (85, 34, 'F', '2022-06-10 20:12:44', '12/9/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (67, 72, 'M', '2022-03-14 11:00:15', '12/28/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (94, 29, 'M', '2022-09-14 21:35:53', '9/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (13, 34, 'M', '2021-11-25 11:14:16', '1/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (95, 33, 'F', '2022-09-18 14:40:42', '10/21/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (71, 40, 'F', '2022-09-22 06:10:34', '9/30/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (58, 42, 'M', '2022-10-08 18:04:01', '4/14/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (27, 92, 'M', '2021-11-21 10:52:45', '3/24/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 85, 'M', '2021-11-06 04:16:42', '12/31/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (4, 8, 'F', '2022-08-16 20:27:40', '11/8/2021');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (68, 61, 'M', '2022-03-16 03:47:55', '6/15/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (17, 99, 'F', '2022-05-02 03:34:41', '8/20/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (58, 61, 'F', '2022-09-28 06:54:18', '9/23/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (51, 86, 'F', '2022-09-06 04:23:18', '3/27/2022');
insert into illness (medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (19, 100, 'M', '2022-08-14 14:08:30', '6/22/2022');

-- person_data
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Burkitt', 'Conan', '4/21/2022', 98, 'M', 2, 1, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Roelvink', 'Flossi', '9/15/2022', 52, 'F', 97, 40, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bingham', 'Melisse', '8/24/2022', 63, 'F', 64, 89, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Enns', 'Katherina', '5/11/2022', 53, 'F', 55, 69, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Corzon', 'Alair', '6/22/2022', 35, 'M', 68, 65, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dempsey', 'Bevin', '1/31/2022', 89, 'M', 9, 6, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Durham', 'Clarita', '7/29/2022', 64, 'F', 87, 19, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bugby', 'Archambault', '3/22/2022', 58, 'M', 30, 13, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Crummy', 'Bartlett', '5/7/2022', 57, 'M', 92, 23, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Crevy', 'Karrie', '10/26/2021', 6, 'F', 54, 29, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bothe', 'Sybil', '6/10/2022', 28, 'F', 28, 64, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('O''Caherny', 'Isabella', '4/2/2022', 46, 'F', 71, 4, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bucktharp', 'Rainer', '11/21/2021', 14, 'M', 46, 60, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Jados', 'Saunderson', '4/13/2022', 45, 'M', 12, 23, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Barnet', 'Lilian', '3/11/2022', 87, 'F', 12, 5, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Palatini', 'Huntington', '6/13/2022', 31, 'M', 66, 70, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Slucock', 'Cynthia', '7/13/2022', 62, 'F', 72, 97, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Burkman', 'Yuma', '10/5/2022', 39, 'M', 93, 8, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Stennes', 'Prissie', '10/17/2022', 14, 'F', 85, 76, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Beslier', 'Haslett', '11/18/2021', 66, 'M', 86, 91, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Grigoire', 'Janifer', '2/20/2022', 53, 'F', 41, 22, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dawtre', 'Garfield', '8/13/2022', 36, 'M', 7, 63, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Grandham', 'Ermin', '12/24/2021', 85, 'M', 31, 40, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Teasdale-Markie', 'Morganne', '12/18/2021', 6, 'F', 58, 43, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Goodhew', 'Lissa', '11/8/2021', 79, 'F', 43, 69, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Rix', 'Floris', '12/7/2021', 67, 'F', 21, 15, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Schneidau', 'Maryrose', '11/3/2021', 12, 'F', 41, 37, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bysouth', 'Ambros', '8/7/2022', 29, 'M', 37, 26, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Redgrove', 'Robinet', '5/3/2022', 36, 'M', 28, 90, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Courtney', 'Dinah', '3/19/2022', 35, 'F', 47, 39, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Burkin', 'Griselda', '7/8/2022', 52, 'F', 20, 79, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('De Hoogh', 'Teena', '7/25/2022', 34, 'F', 97, 7, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dumingo', 'Hugo', '6/28/2022', 35, 'M', 11, 79, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Syder', 'Elden', '4/13/2022', 94, 'M', 59, 42, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Harlock', 'Rebbecca', '4/28/2022', 37, 'F', 25, 18, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Clemmens', 'Tedd', '8/14/2022', 24, 'M', 77, 61, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ferreres', 'Thurston', '3/5/2022', 49, 'M', 97, 57, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ciccerale', 'Wallache', '6/21/2022', 58, 'M', 54, 57, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Camacke', 'Sophronia', '3/13/2022', 83, 'F', 31, 54, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Panton', 'Brana', '9/15/2022', 86, 'F', 89, 45, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Liveing', 'Koenraad', '12/4/2021', 37, 'M', 16, 97, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Fallanche', 'Cornall', '11/5/2021', 99, 'M', 59, 96, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Amsberger', 'Rebecca', '7/14/2022', 86, 'F', 81, 71, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dybell', 'Colet', '8/12/2022', 39, 'M', 77, 35, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Cokayne', 'Lonna', '4/29/2022', 18, 'F', 23, 79, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Huffa', 'Kacey', '11/5/2021', 76, 'F', 89, 4, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Wilkie', 'Ruperto', '4/28/2022', 35, 'M', 68, 50, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Harmour', 'Berget', '7/12/2022', 91, 'F', 75, 61, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Muldoon', 'Madelina', '7/26/2022', 71, 'F', 32, 61, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Alpe', 'Gaston', '11/28/2021', 86, 'M', 48, 90, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Stanbrooke', 'Lucretia', '10/24/2021', 45, 'F', 99, 60, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Kirsch', 'Darnell', '5/15/2022', 74, 'M', 19, 45, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ramalho', 'Mathias', '1/6/2022', 93, 'M', 67, 3, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('McCumskay', 'Amabel', '8/18/2022', 20, 'F', 45, 92, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bellard', 'Lindy', '12/22/2021', 32, 'M', 65, 17, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ratt', 'Amitie', '12/19/2021', 3, 'F', 100, 57, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Mackrell', 'Juanita', '7/13/2022', 23, 'F', 77, 88, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Macenzy', 'Tyrus', '7/3/2022', 52, 'M', 31, 63, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Salvador', 'Persis', '6/8/2022', 24, 'F', 12, 66, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('McCreary', 'Tan', '1/20/2022', 52, 'M', 20, 62, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Davidovitch', 'Blake', '2/25/2022', 71, 'F', 24, 69, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('McDonald', 'Redd', '8/12/2022', 48, 'M', 33, 91, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dannehl', 'Saul', '3/29/2022', 67, 'M', 3, 52, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Martinot', 'Herculie', '8/10/2022', 57, 'M', 55, 48, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Simonnin', 'Charin', '11/9/2021', 12, 'F', 60, 60, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Culverhouse', 'Hailee', '11/4/2021', 54, 'F', 13, 67, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bollon', 'Annabelle', '12/15/2021', 84, 'F', 11, 83, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Paula', 'Matty', '11/23/2021', 28, 'M', 52, 60, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Artindale', 'Sheffield', '8/13/2022', 69, 'M', 2, 99, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Tiuit', 'Michelina', '12/26/2021', 7, 'F', 80, 64, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('MacCarroll', 'Caritta', '3/25/2022', 75, 'F', 65, 64, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Mantrip', 'Lind', '4/18/2022', 45, 'M', 79, 10, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Yarrington', 'Leland', '1/22/2022', 20, 'F', 47, 3, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Cobon', 'Theodore', '11/9/2021', 98, 'M', 57, 27, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Tompsett', 'Keane', '11/4/2021', 75, 'M', 23, 88, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Faithfull', 'Cacilia', '9/19/2022', 24, 'F', 88, 69, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Chessel', 'Royce', '9/23/2022', 98, 'M', 4, 11, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Winchcombe', 'Dacey', '12/9/2021', 70, 'F', 39, 44, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ingraham', 'Catha', '9/30/2022', 24, 'F', 46, 87, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Binley', 'Rab', '8/26/2022', 24, 'M', 58, 97, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Rothchild', 'Vinnie', '9/16/2022', 46, 'F', 56, 94, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Healeas', 'Darya', '12/28/2021', 13, 'F', 26, 11, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Blackhurst', 'Abbe', '7/8/2022', 78, 'F', 76, 56, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Penwright', 'Tailor', '2/21/2022', 32, 'M', 39, 19, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ferrulli', 'Lorinda', '2/14/2022', 50, 'F', 67, 31, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Spore', 'Bron', '3/31/2022', 53, 'M', 75, 63, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Hince', 'Katharina', '5/1/2022', 32, 'F', 100, 92, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Stewart', 'Elane', '9/28/2022', 62, 'F', 73, 10, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Cristofalo', 'Barry', '4/6/2022', 95, 'F', 83, 57, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('O'' Clovan', 'Aloin', '9/6/2022', 74, 'M', 98, 82, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ivery', 'Etienne', '6/15/2022', 85, 'M', 24, 8, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('McLeish', 'Frankie', '8/9/2022', 90, 'F', 67, 49, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Brayn', 'Kellen', '1/24/2022', 28, 'M', 7, 40, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Tanzer', 'Chandal', '9/2/2022', 89, 'F', 44, 36, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Darleston', 'Sebastian', '11/28/2021', 99, 'M', 17, 78, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Trewinnard', 'Bennett', '8/7/2022', 47, 'M', 21, 1, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ingarfield', 'Pamela', '8/6/2022', 11, 'F', 29, 81, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Raithbie', 'Catharina', '8/31/2022', 8, 'F', 10, 59, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Balham', 'Norene', '2/25/2022', 73, 'F', 36, 30, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Blackbourn', 'Ferd', '4/18/2022', 85, 'M', 23, 25, null);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Howsden', 'Karon', '9/29/2022', 2, 'F', 58, 9, 83);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Canadine', 'Gard', '12/30/2021', 61, 'M', 61, 15, 77);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ruddock', 'Ermanno', '12/25/2021', 54, 'M', 81, 66, 34);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Fairbrace', 'Wilhelmine', '11/5/2021', 84, 'F', 89, 74, 21);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Soldi', 'Bette', '8/1/2022', 18, 'F', 97, 15, 50);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Fleg', 'Kristin', '8/25/2022', 19, 'F', 9, 83, 11);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Crennan', 'Martita', '12/21/2021', 36, 'F', 16, 80, 33);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Driussi', 'Myrtia', '12/27/2021', 12, 'F', 29, 2, 56);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Broker', 'Lezlie', '1/30/2022', 16, 'F', 62, 93, 54);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Hydes', 'Bernarr', '12/7/2021', 34, 'M', 71, 5, 63);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Capper', 'Loralie', '6/23/2022', 23, 'F', 47, 51, 63);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Surgeoner', 'Janelle', '11/19/2021', 86, 'F', 39, 26, 79);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Coleford', 'Sim', '4/17/2022', 26, 'M', 19, 35, 17);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Hartness', 'Philipa', '3/25/2022', 29, 'F', 70, 28, 63);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lunny', 'Karry', '10/10/2022', 39, 'F', 25, 5, 34);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Massimi', 'Cloe', '11/13/2021', 78, 'F', 86, 10, 95);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Stickells', 'Brandy', '2/28/2022', 97, 'F', 100, 9, 41);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Mulcaster', 'Ddene', '3/27/2022', 25, 'F', 38, 9, 5);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Baudinet', 'Jacobo', '6/27/2022', 1, 'M', 58, 62, 40);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lympany', 'Chrotoem', '3/6/2022', 55, 'M', 95, 63, 42);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dowry', 'Hedy', '9/5/2022', 49, 'F', 15, 57, 19);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bimson', 'Tommie', '8/29/2022', 71, 'M', 67, 40, 91);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Carah', 'Tresa', '2/17/2022', 97, 'F', 88, 75, 50);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('MacTague', 'Anson', '6/15/2022', 60, 'M', 42, 47, 95);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Doughty', 'Aurie', '11/29/2021', 54, 'F', 90, 81, 37);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Hadgraft', 'Martha', '10/17/2022', 32, 'F', 32, 86, 89);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lorenz', 'Bianca', '9/28/2022', 98, 'F', 92, 3, 30);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Yitzovitz', 'Dukey', '10/25/2021', 66, 'M', 85, 53, 6);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('O''Henehan', 'Raynor', '10/29/2021', 95, 'M', 8, 5, 31);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Passfield', 'Erie', '7/17/2022', 32, 'M', 9, 93, 14);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Noen', 'Gustavus', '2/25/2022', 60, 'M', 19, 30, 69);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Furlonge', 'Free', '4/1/2022', 98, 'M', 2, 48, 51);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bruhnicke', 'Rhody', '8/5/2022', 17, 'F', 93, 55, 57);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Walewicz', 'Sheryl', '2/9/2022', 66, 'F', 19, 92, 99);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Gerrelt', 'Bryn', '3/22/2022', 67, 'F', 80, 83, 91);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lackington', 'Chrissy', '5/23/2022', 58, 'M', 90, 80, 11);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Thewlis', 'Consolata', '12/29/2021', 41, 'F', 72, 57, 4);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ciciotti', 'Warren', '9/21/2022', 92, 'M', 69, 12, 90);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lawie', 'Millie', '11/10/2021', 94, 'F', 12, 93, 100);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Isaac', 'Kareem', '4/5/2022', 2, 'M', 36, 61, 65);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Danilov', 'Peria', '2/11/2022', 9, 'F', 59, 4, 22);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ellif', 'Webster', '3/19/2022', 84, 'M', 68, 99, 40);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Berney', 'Erika', '11/1/2021', 1, 'F', 57, 2, 11);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Benet', 'Jamey', '5/7/2022', 66, 'M', 22, 55, 57);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Nehlsen', 'Corene', '6/11/2022', 8, 'F', 25, 91, 48);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Tipling', 'Donny', '4/10/2022', 100, 'F', 45, 30, 69);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ankers', 'Tiffanie', '8/17/2022', 49, 'F', 22, 84, 49);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Weddup', 'Raddy', '10/9/2022', 56, 'M', 79, 38, 46);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Ellyatt', 'Fedora', '5/2/2022', 41, 'F', 10, 52, 77);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bear', 'Thomasin', '12/28/2021', 3, 'F', 76, 33, 31);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Haseley', 'Phaidra', '8/18/2022', 65, 'F', 52, 41, 18);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Egle', 'Tobey', '7/28/2022', 49, 'F', 28, 87, 28);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Leppard', 'Florette', '5/8/2022', 59, 'F', 70, 39, 78);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Rippingall', 'Tally', '12/18/2021', 7, 'F', 80, 89, 73);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Hobell', 'Jacinda', '7/18/2022', 33, 'F', 59, 33, 51);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Portwaine', 'Mycah', '4/21/2022', 28, 'M', 68, 54, 8);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Scamaden', 'Sarine', '1/25/2022', 33, 'F', 1, 88, 70);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Jeanon', 'Ulrick', '4/28/2022', 1, 'M', 76, 23, 82);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Henrych', 'Koressa', '9/4/2022', 93, 'F', 49, 97, 100);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Nice', 'Andrus', '11/13/2021', 30, 'M', 9, 24, 8);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Schruur', 'Flint', '12/15/2021', 34, 'M', 36, 91, 68);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Gillbe', 'Packston', '7/16/2022', 88, 'M', 72, 94, 74);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Cohrs', 'Harcourt', '1/12/2022', 60, 'M', 84, 33, 54);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('McCusker', 'Penny', '9/5/2022', 75, 'M', 71, 89, 87);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Eilhersen', 'Iosep', '11/1/2021', 56, 'M', 84, 61, 98);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Mazonowicz', 'Beck', '2/1/2022', 10, 'M', 93, 14, 49);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Holt', 'Baily', '9/29/2022', 46, 'M', 72, 7, 40);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('David', 'Haleigh', '4/23/2022', 64, 'F', 27, 21, 87);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Leighton', 'Michal', '3/30/2022', 70, 'F', 58, 65, 65);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Brabender', 'Dane', '6/11/2022', 10, 'M', 22, 56, 22);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Boone', 'Reece', '4/10/2022', 47, 'M', 5, 88, 35);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Label', 'Elysee', '8/8/2022', 86, 'F', 36, 99, 92);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Gobolos', 'Brenda', '9/19/2022', 92, 'F', 33, 84, 97);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Butcher', 'Perle', '2/13/2022', 67, 'F', 5, 81, 98);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Gasticke', 'Adan', '2/5/2022', 8, 'M', 28, 81, 9);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Dryburgh', 'Lu', '2/5/2022', 97, 'F', 9, 2, 9);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Iorillo', 'Bevon', '5/8/2022', 36, 'M', 56, 36, 81);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Logie', 'Lyn', '12/16/2021', 11, 'F', 69, 96, 99);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('MacKegg', 'Lyn', '12/9/2021', 82, 'F', 72, 5, 12);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Emberton', 'Irene', '4/27/2022', 85, 'F', 72, 97, 78);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Filipic', 'Gustie', '10/13/2022', 29, 'F', 35, 12, 89);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Derr', 'Hakeem', '5/26/2022', 53, 'M', 77, 43, 70);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Crighten', 'Amelia', '12/1/2021', 24, 'F', 54, 40, 79);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Prynne', 'Gualterio', '12/17/2021', 37, 'M', 78, 21, 72);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Quene', 'Conroy', '1/10/2022', 75, 'M', 34, 64, 9);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Kilminster', 'Nathaniel', '4/6/2022', 63, 'M', 2, 51, 51);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Portinari', 'Archaimbaud', '10/21/2022', 63, 'M', 14, 8, 46);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Mendoza', 'Caryl', '6/20/2022', 80, 'M', 25, 8, 77);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Kaser', 'Neville', '10/9/2022', 85, 'M', 1, 95, 35);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Alten', 'Dominique', '1/21/2022', 23, 'M', 76, 37, 16);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Kupis', 'Chane', '8/5/2022', 74, 'M', 74, 33, 80);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Bram', 'Lemuel', '7/4/2022', 97, 'M', 61, 90, 99);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Symondson', 'Efrem', '4/30/2022', 19, 'M', 5, 5, 73);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Serfati', 'Chanda', '8/23/2022', 76, 'F', 67, 61, 55);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Garwill', 'Alvy', '11/26/2021', 48, 'M', 18, 47, 20);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Lamort', 'Cristiano', '8/23/2022', 68, 'M', 39, 3, 59);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Faulconer', 'Brewer', '4/18/2022', 48, 'M', 11, 37, 27);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Skittle', 'Maximo', '9/16/2022', 20, 'M', 73, 30, 42);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Threadgold', 'Cyril', '9/18/2022', 84, 'M', 55, 35, 56);
insert into person_data (last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values ('Le Galle', 'Filmer', '9/6/2022', 73, 'M', 24, 38, 43);
