server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
      username: ${DB_LOGIN:root}
      password: ${DB_PASSWORD:root}
      schema: medical

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  messages:
    basename: validation

  liquibase:
    change-log: db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:true}
    default-schema: medical

  main:
    allow-circular-references: true

mybatis:
  configuration:
    autoMappingUnknownColumnBehavior: warning
    map-underscore-to-camel-case: true