server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres}
      username: ${DB_LOGIN:postgres}
      password: ${DB_PASSWORD:root}
      schema: medical

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  messages:
    basename: validation

  liquibase:
    change-log: db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:true}
    default-schema: medical

  main:
    allow-circular-references: true
    banner-mode: off

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.jdbc.core: TRACE

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, loggers"